// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sl_global.proto

#include "sl_global.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG
namespace service_layer {
constexpr SLInitMsg::SLInitMsg(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : majorver_(0u)
  , minorver_(0u)
  , subver_(0u){}
struct SLInitMsgDefaultTypeInternal {
  constexpr SLInitMsgDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~SLInitMsgDefaultTypeInternal() {}
  union {
    SLInitMsg _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT SLInitMsgDefaultTypeInternal _SLInitMsg_default_instance_;
constexpr SLInitMsgRsp::SLInitMsgRsp(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : majorver_(0u)
  , minorver_(0u)
  , subver_(0u){}
struct SLInitMsgRspDefaultTypeInternal {
  constexpr SLInitMsgRspDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~SLInitMsgRspDefaultTypeInternal() {}
  union {
    SLInitMsgRsp _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT SLInitMsgRspDefaultTypeInternal _SLInitMsgRsp_default_instance_;
constexpr SLVrfRouteReplayErrorNotif::SLVrfRouteReplayErrorNotif(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : vrfname_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string){}
struct SLVrfRouteReplayErrorNotifDefaultTypeInternal {
  constexpr SLVrfRouteReplayErrorNotifDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~SLVrfRouteReplayErrorNotifDefaultTypeInternal() {}
  union {
    SLVrfRouteReplayErrorNotif _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT SLVrfRouteReplayErrorNotifDefaultTypeInternal _SLVrfRouteReplayErrorNotif_default_instance_;
constexpr SLGlobalNotif::SLGlobalNotif(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : errstatus_(nullptr)
  , eventtype_(0)

  , _oneof_case_{}{}
struct SLGlobalNotifDefaultTypeInternal {
  constexpr SLGlobalNotifDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~SLGlobalNotifDefaultTypeInternal() {}
  union {
    SLGlobalNotif _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT SLGlobalNotifDefaultTypeInternal _SLGlobalNotif_default_instance_;
constexpr SLGlobalsGetMsg::SLGlobalsGetMsg(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized){}
struct SLGlobalsGetMsgDefaultTypeInternal {
  constexpr SLGlobalsGetMsgDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~SLGlobalsGetMsgDefaultTypeInternal() {}
  union {
    SLGlobalsGetMsg _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT SLGlobalsGetMsgDefaultTypeInternal _SLGlobalsGetMsg_default_instance_;
constexpr SLGlobalsGetMsgRsp::SLGlobalsGetMsgRsp(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : errstatus_(nullptr)
  , maxvrfnamelength_(0u)
  , maxinterfacenamelength_(0u)
  , maxpathsperentry_(0u)
  , maxprimarypathperentry_(0u)
  , maxbackuppathperentry_(0u)
  , maxmplslabelsperpath_(0u)
  , minprimarypathidnum_(0u)
  , maxprimarypathidnum_(0u)
  , minbackuppathidnum_(0u)
  , maxbackuppathidnum_(0u)
  , maxremoteaddressnum_(0u)
  , maxl2bdnamelength_(0u)
  , maxl2pmsitunnelidlength_(0u)
  , maxlabelblockclientnamelength_(0u)
  , maxpathsinnexthopnotif_(0u)
  , maxvrfregpermsg_(0u)
  , maxafopspermsg_(0u)
  , maxnotifreqperslafnotifreq_(0u){}
struct SLGlobalsGetMsgRspDefaultTypeInternal {
  constexpr SLGlobalsGetMsgRspDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~SLGlobalsGetMsgRspDefaultTypeInternal() {}
  union {
    SLGlobalsGetMsgRsp _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT SLGlobalsGetMsgRspDefaultTypeInternal _SLGlobalsGetMsgRsp_default_instance_;
}  // namespace service_layer
static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_sl_5fglobal_2eproto[6];
static const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* file_level_enum_descriptors_sl_5fglobal_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_sl_5fglobal_2eproto = nullptr;

const uint32_t TableStruct_sl_5fglobal_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::service_layer::SLInitMsg, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::service_layer::SLInitMsg, majorver_),
  PROTOBUF_FIELD_OFFSET(::service_layer::SLInitMsg, minorver_),
  PROTOBUF_FIELD_OFFSET(::service_layer::SLInitMsg, subver_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::service_layer::SLInitMsgRsp, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::service_layer::SLInitMsgRsp, majorver_),
  PROTOBUF_FIELD_OFFSET(::service_layer::SLInitMsgRsp, minorver_),
  PROTOBUF_FIELD_OFFSET(::service_layer::SLInitMsgRsp, subver_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::service_layer::SLVrfRouteReplayErrorNotif, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::service_layer::SLVrfRouteReplayErrorNotif, vrfname_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::service_layer::SLGlobalNotif, _internal_metadata_),
  ~0u,  // no _extensions_
  PROTOBUF_FIELD_OFFSET(::service_layer::SLGlobalNotif, _oneof_case_[0]),
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::service_layer::SLGlobalNotif, eventtype_),
  PROTOBUF_FIELD_OFFSET(::service_layer::SLGlobalNotif, errstatus_),
  ::PROTOBUF_NAMESPACE_ID::internal::kInvalidFieldOffsetTag,
  ::PROTOBUF_NAMESPACE_ID::internal::kInvalidFieldOffsetTag,
  PROTOBUF_FIELD_OFFSET(::service_layer::SLGlobalNotif, Event_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::service_layer::SLGlobalsGetMsg, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::service_layer::SLGlobalsGetMsgRsp, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::service_layer::SLGlobalsGetMsgRsp, errstatus_),
  PROTOBUF_FIELD_OFFSET(::service_layer::SLGlobalsGetMsgRsp, maxvrfnamelength_),
  PROTOBUF_FIELD_OFFSET(::service_layer::SLGlobalsGetMsgRsp, maxinterfacenamelength_),
  PROTOBUF_FIELD_OFFSET(::service_layer::SLGlobalsGetMsgRsp, maxpathsperentry_),
  PROTOBUF_FIELD_OFFSET(::service_layer::SLGlobalsGetMsgRsp, maxprimarypathperentry_),
  PROTOBUF_FIELD_OFFSET(::service_layer::SLGlobalsGetMsgRsp, maxbackuppathperentry_),
  PROTOBUF_FIELD_OFFSET(::service_layer::SLGlobalsGetMsgRsp, maxmplslabelsperpath_),
  PROTOBUF_FIELD_OFFSET(::service_layer::SLGlobalsGetMsgRsp, minprimarypathidnum_),
  PROTOBUF_FIELD_OFFSET(::service_layer::SLGlobalsGetMsgRsp, maxprimarypathidnum_),
  PROTOBUF_FIELD_OFFSET(::service_layer::SLGlobalsGetMsgRsp, minbackuppathidnum_),
  PROTOBUF_FIELD_OFFSET(::service_layer::SLGlobalsGetMsgRsp, maxbackuppathidnum_),
  PROTOBUF_FIELD_OFFSET(::service_layer::SLGlobalsGetMsgRsp, maxremoteaddressnum_),
  PROTOBUF_FIELD_OFFSET(::service_layer::SLGlobalsGetMsgRsp, maxl2bdnamelength_),
  PROTOBUF_FIELD_OFFSET(::service_layer::SLGlobalsGetMsgRsp, maxl2pmsitunnelidlength_),
  PROTOBUF_FIELD_OFFSET(::service_layer::SLGlobalsGetMsgRsp, maxlabelblockclientnamelength_),
  PROTOBUF_FIELD_OFFSET(::service_layer::SLGlobalsGetMsgRsp, maxpathsinnexthopnotif_),
  PROTOBUF_FIELD_OFFSET(::service_layer::SLGlobalsGetMsgRsp, maxvrfregpermsg_),
  PROTOBUF_FIELD_OFFSET(::service_layer::SLGlobalsGetMsgRsp, maxafopspermsg_),
  PROTOBUF_FIELD_OFFSET(::service_layer::SLGlobalsGetMsgRsp, maxnotifreqperslafnotifreq_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::service_layer::SLInitMsg)},
  { 9, -1, -1, sizeof(::service_layer::SLInitMsgRsp)},
  { 18, -1, -1, sizeof(::service_layer::SLVrfRouteReplayErrorNotif)},
  { 25, -1, -1, sizeof(::service_layer::SLGlobalNotif)},
  { 36, -1, -1, sizeof(::service_layer::SLGlobalsGetMsg)},
  { 42, -1, -1, sizeof(::service_layer::SLGlobalsGetMsgRsp)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::service_layer::_SLInitMsg_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::service_layer::_SLInitMsgRsp_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::service_layer::_SLVrfRouteReplayErrorNotif_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::service_layer::_SLGlobalNotif_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::service_layer::_SLGlobalsGetMsg_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::service_layer::_SLGlobalsGetMsgRsp_default_instance_),
};

const char descriptor_table_protodef_sl_5fglobal_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\017sl_global.proto\022\rservice_layer\032\025sl_com"
  "mon_types.proto\"\?\n\tSLInitMsg\022\020\n\010MajorVer"
  "\030\001 \001(\r\022\020\n\010MinorVer\030\002 \001(\r\022\016\n\006SubVer\030\003 \001(\r"
  "\"B\n\014SLInitMsgRsp\022\020\n\010MajorVer\030\001 \001(\r\022\020\n\010Mi"
  "norVer\030\002 \001(\r\022\016\n\006SubVer\030\003 \001(\r\"-\n\032SLVrfRou"
  "teReplayErrorNotif\022\017\n\007VrfName\030\001 \001(\t\"\377\001\n\r"
  "SLGlobalNotif\0223\n\tEventType\030\001 \001(\0162 .servi"
  "ce_layer.SLGlobalNotifType\022/\n\tErrStatus\030"
  "\002 \001(\0132\034.service_layer.SLErrorStatus\0221\n\nI"
  "nitRspMsg\030\003 \001(\0132\033.service_layer.SLInitMs"
  "gRspH\000\022L\n\023VrfReplayErrorNotif\030\004 \001(\0132).se"
  "rvice_layer.SLVrfRouteReplayErrorNotifB\002"
  "\030\001H\000B\007\n\005Event\"\021\n\017SLGlobalsGetMsg\"\335\004\n\022SLG"
  "lobalsGetMsgRsp\022/\n\tErrStatus\030\001 \001(\0132\034.ser"
  "vice_layer.SLErrorStatus\022\030\n\020MaxVrfNameLe"
  "ngth\030\002 \001(\r\022\036\n\026MaxInterfaceNameLength\030\003 \001"
  "(\r\022\030\n\020MaxPathsPerEntry\030\004 \001(\r\022\036\n\026MaxPrima"
  "ryPathPerEntry\030\005 \001(\r\022\035\n\025MaxBackupPathPer"
  "Entry\030\006 \001(\r\022\034\n\024MaxMplsLabelsPerPath\030\007 \001("
  "\r\022\033\n\023MinPrimaryPathIdNum\030\010 \001(\r\022\033\n\023MaxPri"
  "maryPathIdNum\030\t \001(\r\022\032\n\022MinBackupPathIdNu"
  "m\030\n \001(\r\022\032\n\022MaxBackupPathIdNum\030\013 \001(\r\022\033\n\023M"
  "axRemoteAddressNum\030\014 \001(\r\022\031\n\021MaxL2BdNameL"
  "ength\030\r \001(\r\022\037\n\027MaxL2PmsiTunnelIdLength\030\016"
  " \001(\r\022%\n\035MaxLabelBlockClientNameLength\030\017 "
  "\001(\r\022\036\n\026MaxPathsInNexthopNotif\030\020 \001(\r\022\027\n\017M"
  "axVrfRegPerMsg\030\021 \001(\r\022\026\n\016MaxAFOpsPerMsg\030\022"
  " \001(\r\022\"\n\032MaxNotifReqPerSLAFNotifReq\030\023 \001(\r"
  "*\234\001\n\021SLGlobalNotifType\022!\n\035SL_GLOBAL_EVEN"
  "T_TYPE_RESERVED\020\000\022\036\n\032SL_GLOBAL_EVENT_TYP"
  "E_ERROR\020\001\022\"\n\036SL_GLOBAL_EVENT_TYPE_HEARTB"
  "EAT\020\002\022 \n\034SL_GLOBAL_EVENT_TYPE_VERSION\020\0032"
  "\254\001\n\010SLGlobal\022M\n\021SLGlobalInitNotif\022\030.serv"
  "ice_layer.SLInitMsg\032\034.service_layer.SLGl"
  "obalNotif0\001\022Q\n\014SLGlobalsGet\022\036.service_la"
  "yer.SLGlobalsGetMsg\032!.service_layer.SLGl"
  "obalsGetMsgRspBQZOgithub.com/Cisco-servi"
  "ce-layer/service-layer-objmodel/grpc/pro"
  "tos;service_layerb\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_sl_5fglobal_2eproto_deps[1] = {
  &::descriptor_table_sl_5fcommon_5ftypes_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_sl_5fglobal_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_sl_5fglobal_2eproto = {
  false, false, 1545, descriptor_table_protodef_sl_5fglobal_2eproto, "sl_global.proto", 
  &descriptor_table_sl_5fglobal_2eproto_once, descriptor_table_sl_5fglobal_2eproto_deps, 1, 6,
  schemas, file_default_instances, TableStruct_sl_5fglobal_2eproto::offsets,
  file_level_metadata_sl_5fglobal_2eproto, file_level_enum_descriptors_sl_5fglobal_2eproto, file_level_service_descriptors_sl_5fglobal_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable* descriptor_table_sl_5fglobal_2eproto_getter() {
  return &descriptor_table_sl_5fglobal_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY static ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptorsRunner dynamic_init_dummy_sl_5fglobal_2eproto(&descriptor_table_sl_5fglobal_2eproto);
namespace service_layer {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* SLGlobalNotifType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_sl_5fglobal_2eproto);
  return file_level_enum_descriptors_sl_5fglobal_2eproto[0];
}
bool SLGlobalNotifType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}


// ===================================================================

class SLInitMsg::_Internal {
 public:
};

SLInitMsg::SLInitMsg(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor();
  if (!is_message_owned) {
    RegisterArenaDtor(arena);
  }
  // @@protoc_insertion_point(arena_constructor:service_layer.SLInitMsg)
}
SLInitMsg::SLInitMsg(const SLInitMsg& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&majorver_, &from.majorver_,
    static_cast<size_t>(reinterpret_cast<char*>(&subver_) -
    reinterpret_cast<char*>(&majorver_)) + sizeof(subver_));
  // @@protoc_insertion_point(copy_constructor:service_layer.SLInitMsg)
}

inline void SLInitMsg::SharedCtor() {
::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
    reinterpret_cast<char*>(&majorver_) - reinterpret_cast<char*>(this)),
    0, static_cast<size_t>(reinterpret_cast<char*>(&subver_) -
    reinterpret_cast<char*>(&majorver_)) + sizeof(subver_));
}

SLInitMsg::~SLInitMsg() {
  // @@protoc_insertion_point(destructor:service_layer.SLInitMsg)
  if (GetArenaForAllocation() != nullptr) return;
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

inline void SLInitMsg::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void SLInitMsg::ArenaDtor(void* object) {
  SLInitMsg* _this = reinterpret_cast< SLInitMsg* >(object);
  (void)_this;
}
void SLInitMsg::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void SLInitMsg::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void SLInitMsg::Clear() {
// @@protoc_insertion_point(message_clear_start:service_layer.SLInitMsg)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&majorver_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&subver_) -
      reinterpret_cast<char*>(&majorver_)) + sizeof(subver_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* SLInitMsg::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint32 MajorVer = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          majorver_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 MinorVer = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          minorver_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 SubVer = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          subver_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* SLInitMsg::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:service_layer.SLInitMsg)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 MajorVer = 1;
  if (this->_internal_majorver() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(1, this->_internal_majorver(), target);
  }

  // uint32 MinorVer = 2;
  if (this->_internal_minorver() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(2, this->_internal_minorver(), target);
  }

  // uint32 SubVer = 3;
  if (this->_internal_subver() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(3, this->_internal_subver(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:service_layer.SLInitMsg)
  return target;
}

size_t SLInitMsg::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:service_layer.SLInitMsg)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // uint32 MajorVer = 1;
  if (this->_internal_majorver() != 0) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32SizePlusOne(this->_internal_majorver());
  }

  // uint32 MinorVer = 2;
  if (this->_internal_minorver() != 0) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32SizePlusOne(this->_internal_minorver());
  }

  // uint32 SubVer = 3;
  if (this->_internal_subver() != 0) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32SizePlusOne(this->_internal_subver());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData SLInitMsg::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    SLInitMsg::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*SLInitMsg::GetClassData() const { return &_class_data_; }

void SLInitMsg::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<SLInitMsg *>(to)->MergeFrom(
      static_cast<const SLInitMsg &>(from));
}


void SLInitMsg::MergeFrom(const SLInitMsg& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:service_layer.SLInitMsg)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_majorver() != 0) {
    _internal_set_majorver(from._internal_majorver());
  }
  if (from._internal_minorver() != 0) {
    _internal_set_minorver(from._internal_minorver());
  }
  if (from._internal_subver() != 0) {
    _internal_set_subver(from._internal_subver());
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void SLInitMsg::CopyFrom(const SLInitMsg& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:service_layer.SLInitMsg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SLInitMsg::IsInitialized() const {
  return true;
}

void SLInitMsg::InternalSwap(SLInitMsg* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(SLInitMsg, subver_)
      + sizeof(SLInitMsg::subver_)
      - PROTOBUF_FIELD_OFFSET(SLInitMsg, majorver_)>(
          reinterpret_cast<char*>(&majorver_),
          reinterpret_cast<char*>(&other->majorver_));
}

::PROTOBUF_NAMESPACE_ID::Metadata SLInitMsg::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_sl_5fglobal_2eproto_getter, &descriptor_table_sl_5fglobal_2eproto_once,
      file_level_metadata_sl_5fglobal_2eproto[0]);
}

// ===================================================================

class SLInitMsgRsp::_Internal {
 public:
};

SLInitMsgRsp::SLInitMsgRsp(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor();
  if (!is_message_owned) {
    RegisterArenaDtor(arena);
  }
  // @@protoc_insertion_point(arena_constructor:service_layer.SLInitMsgRsp)
}
SLInitMsgRsp::SLInitMsgRsp(const SLInitMsgRsp& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&majorver_, &from.majorver_,
    static_cast<size_t>(reinterpret_cast<char*>(&subver_) -
    reinterpret_cast<char*>(&majorver_)) + sizeof(subver_));
  // @@protoc_insertion_point(copy_constructor:service_layer.SLInitMsgRsp)
}

inline void SLInitMsgRsp::SharedCtor() {
::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
    reinterpret_cast<char*>(&majorver_) - reinterpret_cast<char*>(this)),
    0, static_cast<size_t>(reinterpret_cast<char*>(&subver_) -
    reinterpret_cast<char*>(&majorver_)) + sizeof(subver_));
}

SLInitMsgRsp::~SLInitMsgRsp() {
  // @@protoc_insertion_point(destructor:service_layer.SLInitMsgRsp)
  if (GetArenaForAllocation() != nullptr) return;
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

inline void SLInitMsgRsp::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void SLInitMsgRsp::ArenaDtor(void* object) {
  SLInitMsgRsp* _this = reinterpret_cast< SLInitMsgRsp* >(object);
  (void)_this;
}
void SLInitMsgRsp::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void SLInitMsgRsp::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void SLInitMsgRsp::Clear() {
// @@protoc_insertion_point(message_clear_start:service_layer.SLInitMsgRsp)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&majorver_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&subver_) -
      reinterpret_cast<char*>(&majorver_)) + sizeof(subver_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* SLInitMsgRsp::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint32 MajorVer = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          majorver_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 MinorVer = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          minorver_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 SubVer = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          subver_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* SLInitMsgRsp::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:service_layer.SLInitMsgRsp)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 MajorVer = 1;
  if (this->_internal_majorver() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(1, this->_internal_majorver(), target);
  }

  // uint32 MinorVer = 2;
  if (this->_internal_minorver() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(2, this->_internal_minorver(), target);
  }

  // uint32 SubVer = 3;
  if (this->_internal_subver() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(3, this->_internal_subver(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:service_layer.SLInitMsgRsp)
  return target;
}

size_t SLInitMsgRsp::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:service_layer.SLInitMsgRsp)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // uint32 MajorVer = 1;
  if (this->_internal_majorver() != 0) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32SizePlusOne(this->_internal_majorver());
  }

  // uint32 MinorVer = 2;
  if (this->_internal_minorver() != 0) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32SizePlusOne(this->_internal_minorver());
  }

  // uint32 SubVer = 3;
  if (this->_internal_subver() != 0) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32SizePlusOne(this->_internal_subver());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData SLInitMsgRsp::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    SLInitMsgRsp::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*SLInitMsgRsp::GetClassData() const { return &_class_data_; }

void SLInitMsgRsp::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<SLInitMsgRsp *>(to)->MergeFrom(
      static_cast<const SLInitMsgRsp &>(from));
}


void SLInitMsgRsp::MergeFrom(const SLInitMsgRsp& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:service_layer.SLInitMsgRsp)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_majorver() != 0) {
    _internal_set_majorver(from._internal_majorver());
  }
  if (from._internal_minorver() != 0) {
    _internal_set_minorver(from._internal_minorver());
  }
  if (from._internal_subver() != 0) {
    _internal_set_subver(from._internal_subver());
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void SLInitMsgRsp::CopyFrom(const SLInitMsgRsp& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:service_layer.SLInitMsgRsp)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SLInitMsgRsp::IsInitialized() const {
  return true;
}

void SLInitMsgRsp::InternalSwap(SLInitMsgRsp* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(SLInitMsgRsp, subver_)
      + sizeof(SLInitMsgRsp::subver_)
      - PROTOBUF_FIELD_OFFSET(SLInitMsgRsp, majorver_)>(
          reinterpret_cast<char*>(&majorver_),
          reinterpret_cast<char*>(&other->majorver_));
}

::PROTOBUF_NAMESPACE_ID::Metadata SLInitMsgRsp::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_sl_5fglobal_2eproto_getter, &descriptor_table_sl_5fglobal_2eproto_once,
      file_level_metadata_sl_5fglobal_2eproto[1]);
}

// ===================================================================

class SLVrfRouteReplayErrorNotif::_Internal {
 public:
};

SLVrfRouteReplayErrorNotif::SLVrfRouteReplayErrorNotif(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor();
  if (!is_message_owned) {
    RegisterArenaDtor(arena);
  }
  // @@protoc_insertion_point(arena_constructor:service_layer.SLVrfRouteReplayErrorNotif)
}
SLVrfRouteReplayErrorNotif::SLVrfRouteReplayErrorNotif(const SLVrfRouteReplayErrorNotif& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  vrfname_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    vrfname_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_vrfname().empty()) {
    vrfname_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_vrfname(), 
      GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:service_layer.SLVrfRouteReplayErrorNotif)
}

inline void SLVrfRouteReplayErrorNotif::SharedCtor() {
vrfname_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  vrfname_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

SLVrfRouteReplayErrorNotif::~SLVrfRouteReplayErrorNotif() {
  // @@protoc_insertion_point(destructor:service_layer.SLVrfRouteReplayErrorNotif)
  if (GetArenaForAllocation() != nullptr) return;
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

inline void SLVrfRouteReplayErrorNotif::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  vrfname_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void SLVrfRouteReplayErrorNotif::ArenaDtor(void* object) {
  SLVrfRouteReplayErrorNotif* _this = reinterpret_cast< SLVrfRouteReplayErrorNotif* >(object);
  (void)_this;
}
void SLVrfRouteReplayErrorNotif::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void SLVrfRouteReplayErrorNotif::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void SLVrfRouteReplayErrorNotif::Clear() {
// @@protoc_insertion_point(message_clear_start:service_layer.SLVrfRouteReplayErrorNotif)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  vrfname_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* SLVrfRouteReplayErrorNotif::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string VrfName = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_vrfname();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "service_layer.SLVrfRouteReplayErrorNotif.VrfName"));
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* SLVrfRouteReplayErrorNotif::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:service_layer.SLVrfRouteReplayErrorNotif)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string VrfName = 1;
  if (!this->_internal_vrfname().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_vrfname().data(), static_cast<int>(this->_internal_vrfname().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "service_layer.SLVrfRouteReplayErrorNotif.VrfName");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_vrfname(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:service_layer.SLVrfRouteReplayErrorNotif)
  return target;
}

size_t SLVrfRouteReplayErrorNotif::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:service_layer.SLVrfRouteReplayErrorNotif)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string VrfName = 1;
  if (!this->_internal_vrfname().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_vrfname());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData SLVrfRouteReplayErrorNotif::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    SLVrfRouteReplayErrorNotif::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*SLVrfRouteReplayErrorNotif::GetClassData() const { return &_class_data_; }

void SLVrfRouteReplayErrorNotif::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<SLVrfRouteReplayErrorNotif *>(to)->MergeFrom(
      static_cast<const SLVrfRouteReplayErrorNotif &>(from));
}


void SLVrfRouteReplayErrorNotif::MergeFrom(const SLVrfRouteReplayErrorNotif& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:service_layer.SLVrfRouteReplayErrorNotif)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_vrfname().empty()) {
    _internal_set_vrfname(from._internal_vrfname());
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void SLVrfRouteReplayErrorNotif::CopyFrom(const SLVrfRouteReplayErrorNotif& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:service_layer.SLVrfRouteReplayErrorNotif)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SLVrfRouteReplayErrorNotif::IsInitialized() const {
  return true;
}

void SLVrfRouteReplayErrorNotif::InternalSwap(SLVrfRouteReplayErrorNotif* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      &vrfname_, lhs_arena,
      &other->vrfname_, rhs_arena
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata SLVrfRouteReplayErrorNotif::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_sl_5fglobal_2eproto_getter, &descriptor_table_sl_5fglobal_2eproto_once,
      file_level_metadata_sl_5fglobal_2eproto[2]);
}

// ===================================================================

class SLGlobalNotif::_Internal {
 public:
  static const ::service_layer::SLErrorStatus& errstatus(const SLGlobalNotif* msg);
  static const ::service_layer::SLInitMsgRsp& initrspmsg(const SLGlobalNotif* msg);
  static const ::service_layer::SLVrfRouteReplayErrorNotif& vrfreplayerrornotif(const SLGlobalNotif* msg);
};

const ::service_layer::SLErrorStatus&
SLGlobalNotif::_Internal::errstatus(const SLGlobalNotif* msg) {
  return *msg->errstatus_;
}
const ::service_layer::SLInitMsgRsp&
SLGlobalNotif::_Internal::initrspmsg(const SLGlobalNotif* msg) {
  return *msg->Event_.initrspmsg_;
}
const ::service_layer::SLVrfRouteReplayErrorNotif&
SLGlobalNotif::_Internal::vrfreplayerrornotif(const SLGlobalNotif* msg) {
  return *msg->Event_.vrfreplayerrornotif_;
}
void SLGlobalNotif::clear_errstatus() {
  if (GetArenaForAllocation() == nullptr && errstatus_ != nullptr) {
    delete errstatus_;
  }
  errstatus_ = nullptr;
}
void SLGlobalNotif::set_allocated_initrspmsg(::service_layer::SLInitMsgRsp* initrspmsg) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_Event();
  if (initrspmsg) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<::service_layer::SLInitMsgRsp>::GetOwningArena(initrspmsg);
    if (message_arena != submessage_arena) {
      initrspmsg = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, initrspmsg, submessage_arena);
    }
    set_has_initrspmsg();
    Event_.initrspmsg_ = initrspmsg;
  }
  // @@protoc_insertion_point(field_set_allocated:service_layer.SLGlobalNotif.InitRspMsg)
}
void SLGlobalNotif::set_allocated_vrfreplayerrornotif(::service_layer::SLVrfRouteReplayErrorNotif* vrfreplayerrornotif) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_Event();
  if (vrfreplayerrornotif) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<::service_layer::SLVrfRouteReplayErrorNotif>::GetOwningArena(vrfreplayerrornotif);
    if (message_arena != submessage_arena) {
      vrfreplayerrornotif = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, vrfreplayerrornotif, submessage_arena);
    }
    set_has_vrfreplayerrornotif();
    Event_.vrfreplayerrornotif_ = vrfreplayerrornotif;
  }
  // @@protoc_insertion_point(field_set_allocated:service_layer.SLGlobalNotif.VrfReplayErrorNotif)
}
SLGlobalNotif::SLGlobalNotif(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor();
  if (!is_message_owned) {
    RegisterArenaDtor(arena);
  }
  // @@protoc_insertion_point(arena_constructor:service_layer.SLGlobalNotif)
}
SLGlobalNotif::SLGlobalNotif(const SLGlobalNotif& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_errstatus()) {
    errstatus_ = new ::service_layer::SLErrorStatus(*from.errstatus_);
  } else {
    errstatus_ = nullptr;
  }
  eventtype_ = from.eventtype_;
  clear_has_Event();
  switch (from.Event_case()) {
    case kInitRspMsg: {
      _internal_mutable_initrspmsg()->::service_layer::SLInitMsgRsp::MergeFrom(from._internal_initrspmsg());
      break;
    }
    case kVrfReplayErrorNotif: {
      _internal_mutable_vrfreplayerrornotif()->::service_layer::SLVrfRouteReplayErrorNotif::MergeFrom(from._internal_vrfreplayerrornotif());
      break;
    }
    case EVENT_NOT_SET: {
      break;
    }
  }
  // @@protoc_insertion_point(copy_constructor:service_layer.SLGlobalNotif)
}

inline void SLGlobalNotif::SharedCtor() {
::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
    reinterpret_cast<char*>(&errstatus_) - reinterpret_cast<char*>(this)),
    0, static_cast<size_t>(reinterpret_cast<char*>(&eventtype_) -
    reinterpret_cast<char*>(&errstatus_)) + sizeof(eventtype_));
clear_has_Event();
}

SLGlobalNotif::~SLGlobalNotif() {
  // @@protoc_insertion_point(destructor:service_layer.SLGlobalNotif)
  if (GetArenaForAllocation() != nullptr) return;
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

inline void SLGlobalNotif::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete errstatus_;
  if (has_Event()) {
    clear_Event();
  }
}

void SLGlobalNotif::ArenaDtor(void* object) {
  SLGlobalNotif* _this = reinterpret_cast< SLGlobalNotif* >(object);
  (void)_this;
}
void SLGlobalNotif::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void SLGlobalNotif::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void SLGlobalNotif::clear_Event() {
// @@protoc_insertion_point(one_of_clear_start:service_layer.SLGlobalNotif)
  switch (Event_case()) {
    case kInitRspMsg: {
      if (GetArenaForAllocation() == nullptr) {
        delete Event_.initrspmsg_;
      }
      break;
    }
    case kVrfReplayErrorNotif: {
      if (GetArenaForAllocation() == nullptr) {
        delete Event_.vrfreplayerrornotif_;
      }
      break;
    }
    case EVENT_NOT_SET: {
      break;
    }
  }
  _oneof_case_[0] = EVENT_NOT_SET;
}


void SLGlobalNotif::Clear() {
// @@protoc_insertion_point(message_clear_start:service_layer.SLGlobalNotif)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaForAllocation() == nullptr && errstatus_ != nullptr) {
    delete errstatus_;
  }
  errstatus_ = nullptr;
  eventtype_ = 0;
  clear_Event();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* SLGlobalNotif::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .service_layer.SLGlobalNotifType EventType = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_eventtype(static_cast<::service_layer::SLGlobalNotifType>(val));
        } else
          goto handle_unusual;
        continue;
      // .service_layer.SLErrorStatus ErrStatus = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_errstatus(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .service_layer.SLInitMsgRsp InitRspMsg = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          ptr = ctx->ParseMessage(_internal_mutable_initrspmsg(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .service_layer.SLVrfRouteReplayErrorNotif VrfReplayErrorNotif = 4 [deprecated = true];
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          ptr = ctx->ParseMessage(_internal_mutable_vrfreplayerrornotif(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* SLGlobalNotif::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:service_layer.SLGlobalNotif)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .service_layer.SLGlobalNotifType EventType = 1;
  if (this->_internal_eventtype() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnumToArray(
      1, this->_internal_eventtype(), target);
  }

  // .service_layer.SLErrorStatus ErrStatus = 2;
  if (this->_internal_has_errstatus()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        2, _Internal::errstatus(this), target, stream);
  }

  // .service_layer.SLInitMsgRsp InitRspMsg = 3;
  if (_internal_has_initrspmsg()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        3, _Internal::initrspmsg(this), target, stream);
  }

  // .service_layer.SLVrfRouteReplayErrorNotif VrfReplayErrorNotif = 4 [deprecated = true];
  if (_internal_has_vrfreplayerrornotif()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        4, _Internal::vrfreplayerrornotif(this), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:service_layer.SLGlobalNotif)
  return target;
}

size_t SLGlobalNotif::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:service_layer.SLGlobalNotif)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .service_layer.SLErrorStatus ErrStatus = 2;
  if (this->_internal_has_errstatus()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *errstatus_);
  }

  // .service_layer.SLGlobalNotifType EventType = 1;
  if (this->_internal_eventtype() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->_internal_eventtype());
  }

  switch (Event_case()) {
    // .service_layer.SLInitMsgRsp InitRspMsg = 3;
    case kInitRspMsg: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *Event_.initrspmsg_);
      break;
    }
    // .service_layer.SLVrfRouteReplayErrorNotif VrfReplayErrorNotif = 4 [deprecated = true];
    case kVrfReplayErrorNotif: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *Event_.vrfreplayerrornotif_);
      break;
    }
    case EVENT_NOT_SET: {
      break;
    }
  }
  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData SLGlobalNotif::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    SLGlobalNotif::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*SLGlobalNotif::GetClassData() const { return &_class_data_; }

void SLGlobalNotif::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<SLGlobalNotif *>(to)->MergeFrom(
      static_cast<const SLGlobalNotif &>(from));
}


void SLGlobalNotif::MergeFrom(const SLGlobalNotif& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:service_layer.SLGlobalNotif)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_errstatus()) {
    _internal_mutable_errstatus()->::service_layer::SLErrorStatus::MergeFrom(from._internal_errstatus());
  }
  if (from._internal_eventtype() != 0) {
    _internal_set_eventtype(from._internal_eventtype());
  }
  switch (from.Event_case()) {
    case kInitRspMsg: {
      _internal_mutable_initrspmsg()->::service_layer::SLInitMsgRsp::MergeFrom(from._internal_initrspmsg());
      break;
    }
    case kVrfReplayErrorNotif: {
      _internal_mutable_vrfreplayerrornotif()->::service_layer::SLVrfRouteReplayErrorNotif::MergeFrom(from._internal_vrfreplayerrornotif());
      break;
    }
    case EVENT_NOT_SET: {
      break;
    }
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void SLGlobalNotif::CopyFrom(const SLGlobalNotif& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:service_layer.SLGlobalNotif)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SLGlobalNotif::IsInitialized() const {
  return true;
}

void SLGlobalNotif::InternalSwap(SLGlobalNotif* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(SLGlobalNotif, eventtype_)
      + sizeof(SLGlobalNotif::eventtype_)
      - PROTOBUF_FIELD_OFFSET(SLGlobalNotif, errstatus_)>(
          reinterpret_cast<char*>(&errstatus_),
          reinterpret_cast<char*>(&other->errstatus_));
  swap(Event_, other->Event_);
  swap(_oneof_case_[0], other->_oneof_case_[0]);
}

::PROTOBUF_NAMESPACE_ID::Metadata SLGlobalNotif::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_sl_5fglobal_2eproto_getter, &descriptor_table_sl_5fglobal_2eproto_once,
      file_level_metadata_sl_5fglobal_2eproto[3]);
}

// ===================================================================

class SLGlobalsGetMsg::_Internal {
 public:
};

SLGlobalsGetMsg::SLGlobalsGetMsg(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase(arena, is_message_owned) {
  // @@protoc_insertion_point(arena_constructor:service_layer.SLGlobalsGetMsg)
}
SLGlobalsGetMsg::SLGlobalsGetMsg(const SLGlobalsGetMsg& from)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:service_layer.SLGlobalsGetMsg)
}





const ::PROTOBUF_NAMESPACE_ID::Message::ClassData SLGlobalsGetMsg::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl,
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl,
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*SLGlobalsGetMsg::GetClassData() const { return &_class_data_; }







::PROTOBUF_NAMESPACE_ID::Metadata SLGlobalsGetMsg::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_sl_5fglobal_2eproto_getter, &descriptor_table_sl_5fglobal_2eproto_once,
      file_level_metadata_sl_5fglobal_2eproto[4]);
}

// ===================================================================

class SLGlobalsGetMsgRsp::_Internal {
 public:
  static const ::service_layer::SLErrorStatus& errstatus(const SLGlobalsGetMsgRsp* msg);
};

const ::service_layer::SLErrorStatus&
SLGlobalsGetMsgRsp::_Internal::errstatus(const SLGlobalsGetMsgRsp* msg) {
  return *msg->errstatus_;
}
void SLGlobalsGetMsgRsp::clear_errstatus() {
  if (GetArenaForAllocation() == nullptr && errstatus_ != nullptr) {
    delete errstatus_;
  }
  errstatus_ = nullptr;
}
SLGlobalsGetMsgRsp::SLGlobalsGetMsgRsp(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor();
  if (!is_message_owned) {
    RegisterArenaDtor(arena);
  }
  // @@protoc_insertion_point(arena_constructor:service_layer.SLGlobalsGetMsgRsp)
}
SLGlobalsGetMsgRsp::SLGlobalsGetMsgRsp(const SLGlobalsGetMsgRsp& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_errstatus()) {
    errstatus_ = new ::service_layer::SLErrorStatus(*from.errstatus_);
  } else {
    errstatus_ = nullptr;
  }
  ::memcpy(&maxvrfnamelength_, &from.maxvrfnamelength_,
    static_cast<size_t>(reinterpret_cast<char*>(&maxnotifreqperslafnotifreq_) -
    reinterpret_cast<char*>(&maxvrfnamelength_)) + sizeof(maxnotifreqperslafnotifreq_));
  // @@protoc_insertion_point(copy_constructor:service_layer.SLGlobalsGetMsgRsp)
}

inline void SLGlobalsGetMsgRsp::SharedCtor() {
::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
    reinterpret_cast<char*>(&errstatus_) - reinterpret_cast<char*>(this)),
    0, static_cast<size_t>(reinterpret_cast<char*>(&maxnotifreqperslafnotifreq_) -
    reinterpret_cast<char*>(&errstatus_)) + sizeof(maxnotifreqperslafnotifreq_));
}

SLGlobalsGetMsgRsp::~SLGlobalsGetMsgRsp() {
  // @@protoc_insertion_point(destructor:service_layer.SLGlobalsGetMsgRsp)
  if (GetArenaForAllocation() != nullptr) return;
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

inline void SLGlobalsGetMsgRsp::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete errstatus_;
}

void SLGlobalsGetMsgRsp::ArenaDtor(void* object) {
  SLGlobalsGetMsgRsp* _this = reinterpret_cast< SLGlobalsGetMsgRsp* >(object);
  (void)_this;
}
void SLGlobalsGetMsgRsp::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void SLGlobalsGetMsgRsp::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void SLGlobalsGetMsgRsp::Clear() {
// @@protoc_insertion_point(message_clear_start:service_layer.SLGlobalsGetMsgRsp)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaForAllocation() == nullptr && errstatus_ != nullptr) {
    delete errstatus_;
  }
  errstatus_ = nullptr;
  ::memset(&maxvrfnamelength_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&maxnotifreqperslafnotifreq_) -
      reinterpret_cast<char*>(&maxvrfnamelength_)) + sizeof(maxnotifreqperslafnotifreq_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* SLGlobalsGetMsgRsp::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .service_layer.SLErrorStatus ErrStatus = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_errstatus(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 MaxVrfNameLength = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          maxvrfnamelength_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 MaxInterfaceNameLength = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          maxinterfacenamelength_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 MaxPathsPerEntry = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          maxpathsperentry_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 MaxPrimaryPathPerEntry = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 40)) {
          maxprimarypathperentry_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 MaxBackupPathPerEntry = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 48)) {
          maxbackuppathperentry_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 MaxMplsLabelsPerPath = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 56)) {
          maxmplslabelsperpath_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 MinPrimaryPathIdNum = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 64)) {
          minprimarypathidnum_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 MaxPrimaryPathIdNum = 9;
      case 9:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 72)) {
          maxprimarypathidnum_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 MinBackupPathIdNum = 10;
      case 10:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 80)) {
          minbackuppathidnum_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 MaxBackupPathIdNum = 11;
      case 11:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 88)) {
          maxbackuppathidnum_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 MaxRemoteAddressNum = 12;
      case 12:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 96)) {
          maxremoteaddressnum_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 MaxL2BdNameLength = 13;
      case 13:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 104)) {
          maxl2bdnamelength_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 MaxL2PmsiTunnelIdLength = 14;
      case 14:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 112)) {
          maxl2pmsitunnelidlength_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 MaxLabelBlockClientNameLength = 15;
      case 15:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 120)) {
          maxlabelblockclientnamelength_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 MaxPathsInNexthopNotif = 16;
      case 16:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 128)) {
          maxpathsinnexthopnotif_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 MaxVrfRegPerMsg = 17;
      case 17:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 136)) {
          maxvrfregpermsg_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 MaxAFOpsPerMsg = 18;
      case 18:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 144)) {
          maxafopspermsg_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 MaxNotifReqPerSLAFNotifReq = 19;
      case 19:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 152)) {
          maxnotifreqperslafnotifreq_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* SLGlobalsGetMsgRsp::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:service_layer.SLGlobalsGetMsgRsp)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .service_layer.SLErrorStatus ErrStatus = 1;
  if (this->_internal_has_errstatus()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        1, _Internal::errstatus(this), target, stream);
  }

  // uint32 MaxVrfNameLength = 2;
  if (this->_internal_maxvrfnamelength() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(2, this->_internal_maxvrfnamelength(), target);
  }

  // uint32 MaxInterfaceNameLength = 3;
  if (this->_internal_maxinterfacenamelength() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(3, this->_internal_maxinterfacenamelength(), target);
  }

  // uint32 MaxPathsPerEntry = 4;
  if (this->_internal_maxpathsperentry() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(4, this->_internal_maxpathsperentry(), target);
  }

  // uint32 MaxPrimaryPathPerEntry = 5;
  if (this->_internal_maxprimarypathperentry() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(5, this->_internal_maxprimarypathperentry(), target);
  }

  // uint32 MaxBackupPathPerEntry = 6;
  if (this->_internal_maxbackuppathperentry() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(6, this->_internal_maxbackuppathperentry(), target);
  }

  // uint32 MaxMplsLabelsPerPath = 7;
  if (this->_internal_maxmplslabelsperpath() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(7, this->_internal_maxmplslabelsperpath(), target);
  }

  // uint32 MinPrimaryPathIdNum = 8;
  if (this->_internal_minprimarypathidnum() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(8, this->_internal_minprimarypathidnum(), target);
  }

  // uint32 MaxPrimaryPathIdNum = 9;
  if (this->_internal_maxprimarypathidnum() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(9, this->_internal_maxprimarypathidnum(), target);
  }

  // uint32 MinBackupPathIdNum = 10;
  if (this->_internal_minbackuppathidnum() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(10, this->_internal_minbackuppathidnum(), target);
  }

  // uint32 MaxBackupPathIdNum = 11;
  if (this->_internal_maxbackuppathidnum() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(11, this->_internal_maxbackuppathidnum(), target);
  }

  // uint32 MaxRemoteAddressNum = 12;
  if (this->_internal_maxremoteaddressnum() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(12, this->_internal_maxremoteaddressnum(), target);
  }

  // uint32 MaxL2BdNameLength = 13;
  if (this->_internal_maxl2bdnamelength() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(13, this->_internal_maxl2bdnamelength(), target);
  }

  // uint32 MaxL2PmsiTunnelIdLength = 14;
  if (this->_internal_maxl2pmsitunnelidlength() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(14, this->_internal_maxl2pmsitunnelidlength(), target);
  }

  // uint32 MaxLabelBlockClientNameLength = 15;
  if (this->_internal_maxlabelblockclientnamelength() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(15, this->_internal_maxlabelblockclientnamelength(), target);
  }

  // uint32 MaxPathsInNexthopNotif = 16;
  if (this->_internal_maxpathsinnexthopnotif() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(16, this->_internal_maxpathsinnexthopnotif(), target);
  }

  // uint32 MaxVrfRegPerMsg = 17;
  if (this->_internal_maxvrfregpermsg() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(17, this->_internal_maxvrfregpermsg(), target);
  }

  // uint32 MaxAFOpsPerMsg = 18;
  if (this->_internal_maxafopspermsg() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(18, this->_internal_maxafopspermsg(), target);
  }

  // uint32 MaxNotifReqPerSLAFNotifReq = 19;
  if (this->_internal_maxnotifreqperslafnotifreq() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(19, this->_internal_maxnotifreqperslafnotifreq(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:service_layer.SLGlobalsGetMsgRsp)
  return target;
}

size_t SLGlobalsGetMsgRsp::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:service_layer.SLGlobalsGetMsgRsp)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .service_layer.SLErrorStatus ErrStatus = 1;
  if (this->_internal_has_errstatus()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *errstatus_);
  }

  // uint32 MaxVrfNameLength = 2;
  if (this->_internal_maxvrfnamelength() != 0) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32SizePlusOne(this->_internal_maxvrfnamelength());
  }

  // uint32 MaxInterfaceNameLength = 3;
  if (this->_internal_maxinterfacenamelength() != 0) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32SizePlusOne(this->_internal_maxinterfacenamelength());
  }

  // uint32 MaxPathsPerEntry = 4;
  if (this->_internal_maxpathsperentry() != 0) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32SizePlusOne(this->_internal_maxpathsperentry());
  }

  // uint32 MaxPrimaryPathPerEntry = 5;
  if (this->_internal_maxprimarypathperentry() != 0) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32SizePlusOne(this->_internal_maxprimarypathperentry());
  }

  // uint32 MaxBackupPathPerEntry = 6;
  if (this->_internal_maxbackuppathperentry() != 0) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32SizePlusOne(this->_internal_maxbackuppathperentry());
  }

  // uint32 MaxMplsLabelsPerPath = 7;
  if (this->_internal_maxmplslabelsperpath() != 0) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32SizePlusOne(this->_internal_maxmplslabelsperpath());
  }

  // uint32 MinPrimaryPathIdNum = 8;
  if (this->_internal_minprimarypathidnum() != 0) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32SizePlusOne(this->_internal_minprimarypathidnum());
  }

  // uint32 MaxPrimaryPathIdNum = 9;
  if (this->_internal_maxprimarypathidnum() != 0) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32SizePlusOne(this->_internal_maxprimarypathidnum());
  }

  // uint32 MinBackupPathIdNum = 10;
  if (this->_internal_minbackuppathidnum() != 0) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32SizePlusOne(this->_internal_minbackuppathidnum());
  }

  // uint32 MaxBackupPathIdNum = 11;
  if (this->_internal_maxbackuppathidnum() != 0) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32SizePlusOne(this->_internal_maxbackuppathidnum());
  }

  // uint32 MaxRemoteAddressNum = 12;
  if (this->_internal_maxremoteaddressnum() != 0) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32SizePlusOne(this->_internal_maxremoteaddressnum());
  }

  // uint32 MaxL2BdNameLength = 13;
  if (this->_internal_maxl2bdnamelength() != 0) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32SizePlusOne(this->_internal_maxl2bdnamelength());
  }

  // uint32 MaxL2PmsiTunnelIdLength = 14;
  if (this->_internal_maxl2pmsitunnelidlength() != 0) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32SizePlusOne(this->_internal_maxl2pmsitunnelidlength());
  }

  // uint32 MaxLabelBlockClientNameLength = 15;
  if (this->_internal_maxlabelblockclientnamelength() != 0) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32SizePlusOne(this->_internal_maxlabelblockclientnamelength());
  }

  // uint32 MaxPathsInNexthopNotif = 16;
  if (this->_internal_maxpathsinnexthopnotif() != 0) {
    total_size += 2 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_maxpathsinnexthopnotif());
  }

  // uint32 MaxVrfRegPerMsg = 17;
  if (this->_internal_maxvrfregpermsg() != 0) {
    total_size += 2 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_maxvrfregpermsg());
  }

  // uint32 MaxAFOpsPerMsg = 18;
  if (this->_internal_maxafopspermsg() != 0) {
    total_size += 2 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_maxafopspermsg());
  }

  // uint32 MaxNotifReqPerSLAFNotifReq = 19;
  if (this->_internal_maxnotifreqperslafnotifreq() != 0) {
    total_size += 2 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_maxnotifreqperslafnotifreq());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData SLGlobalsGetMsgRsp::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    SLGlobalsGetMsgRsp::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*SLGlobalsGetMsgRsp::GetClassData() const { return &_class_data_; }

void SLGlobalsGetMsgRsp::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<SLGlobalsGetMsgRsp *>(to)->MergeFrom(
      static_cast<const SLGlobalsGetMsgRsp &>(from));
}


void SLGlobalsGetMsgRsp::MergeFrom(const SLGlobalsGetMsgRsp& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:service_layer.SLGlobalsGetMsgRsp)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_errstatus()) {
    _internal_mutable_errstatus()->::service_layer::SLErrorStatus::MergeFrom(from._internal_errstatus());
  }
  if (from._internal_maxvrfnamelength() != 0) {
    _internal_set_maxvrfnamelength(from._internal_maxvrfnamelength());
  }
  if (from._internal_maxinterfacenamelength() != 0) {
    _internal_set_maxinterfacenamelength(from._internal_maxinterfacenamelength());
  }
  if (from._internal_maxpathsperentry() != 0) {
    _internal_set_maxpathsperentry(from._internal_maxpathsperentry());
  }
  if (from._internal_maxprimarypathperentry() != 0) {
    _internal_set_maxprimarypathperentry(from._internal_maxprimarypathperentry());
  }
  if (from._internal_maxbackuppathperentry() != 0) {
    _internal_set_maxbackuppathperentry(from._internal_maxbackuppathperentry());
  }
  if (from._internal_maxmplslabelsperpath() != 0) {
    _internal_set_maxmplslabelsperpath(from._internal_maxmplslabelsperpath());
  }
  if (from._internal_minprimarypathidnum() != 0) {
    _internal_set_minprimarypathidnum(from._internal_minprimarypathidnum());
  }
  if (from._internal_maxprimarypathidnum() != 0) {
    _internal_set_maxprimarypathidnum(from._internal_maxprimarypathidnum());
  }
  if (from._internal_minbackuppathidnum() != 0) {
    _internal_set_minbackuppathidnum(from._internal_minbackuppathidnum());
  }
  if (from._internal_maxbackuppathidnum() != 0) {
    _internal_set_maxbackuppathidnum(from._internal_maxbackuppathidnum());
  }
  if (from._internal_maxremoteaddressnum() != 0) {
    _internal_set_maxremoteaddressnum(from._internal_maxremoteaddressnum());
  }
  if (from._internal_maxl2bdnamelength() != 0) {
    _internal_set_maxl2bdnamelength(from._internal_maxl2bdnamelength());
  }
  if (from._internal_maxl2pmsitunnelidlength() != 0) {
    _internal_set_maxl2pmsitunnelidlength(from._internal_maxl2pmsitunnelidlength());
  }
  if (from._internal_maxlabelblockclientnamelength() != 0) {
    _internal_set_maxlabelblockclientnamelength(from._internal_maxlabelblockclientnamelength());
  }
  if (from._internal_maxpathsinnexthopnotif() != 0) {
    _internal_set_maxpathsinnexthopnotif(from._internal_maxpathsinnexthopnotif());
  }
  if (from._internal_maxvrfregpermsg() != 0) {
    _internal_set_maxvrfregpermsg(from._internal_maxvrfregpermsg());
  }
  if (from._internal_maxafopspermsg() != 0) {
    _internal_set_maxafopspermsg(from._internal_maxafopspermsg());
  }
  if (from._internal_maxnotifreqperslafnotifreq() != 0) {
    _internal_set_maxnotifreqperslafnotifreq(from._internal_maxnotifreqperslafnotifreq());
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void SLGlobalsGetMsgRsp::CopyFrom(const SLGlobalsGetMsgRsp& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:service_layer.SLGlobalsGetMsgRsp)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SLGlobalsGetMsgRsp::IsInitialized() const {
  return true;
}

void SLGlobalsGetMsgRsp::InternalSwap(SLGlobalsGetMsgRsp* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(SLGlobalsGetMsgRsp, maxnotifreqperslafnotifreq_)
      + sizeof(SLGlobalsGetMsgRsp::maxnotifreqperslafnotifreq_)
      - PROTOBUF_FIELD_OFFSET(SLGlobalsGetMsgRsp, errstatus_)>(
          reinterpret_cast<char*>(&errstatus_),
          reinterpret_cast<char*>(&other->errstatus_));
}

::PROTOBUF_NAMESPACE_ID::Metadata SLGlobalsGetMsgRsp::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_sl_5fglobal_2eproto_getter, &descriptor_table_sl_5fglobal_2eproto_once,
      file_level_metadata_sl_5fglobal_2eproto[5]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace service_layer
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::service_layer::SLInitMsg* Arena::CreateMaybeMessage< ::service_layer::SLInitMsg >(Arena* arena) {
  return Arena::CreateMessageInternal< ::service_layer::SLInitMsg >(arena);
}
template<> PROTOBUF_NOINLINE ::service_layer::SLInitMsgRsp* Arena::CreateMaybeMessage< ::service_layer::SLInitMsgRsp >(Arena* arena) {
  return Arena::CreateMessageInternal< ::service_layer::SLInitMsgRsp >(arena);
}
template<> PROTOBUF_NOINLINE ::service_layer::SLVrfRouteReplayErrorNotif* Arena::CreateMaybeMessage< ::service_layer::SLVrfRouteReplayErrorNotif >(Arena* arena) {
  return Arena::CreateMessageInternal< ::service_layer::SLVrfRouteReplayErrorNotif >(arena);
}
template<> PROTOBUF_NOINLINE ::service_layer::SLGlobalNotif* Arena::CreateMaybeMessage< ::service_layer::SLGlobalNotif >(Arena* arena) {
  return Arena::CreateMessageInternal< ::service_layer::SLGlobalNotif >(arena);
}
template<> PROTOBUF_NOINLINE ::service_layer::SLGlobalsGetMsg* Arena::CreateMaybeMessage< ::service_layer::SLGlobalsGetMsg >(Arena* arena) {
  return Arena::CreateMessageInternal< ::service_layer::SLGlobalsGetMsg >(arena);
}
template<> PROTOBUF_NOINLINE ::service_layer::SLGlobalsGetMsgRsp* Arena::CreateMaybeMessage< ::service_layer::SLGlobalsGetMsgRsp >(Arena* arena) {
  return Arena::CreateMessageInternal< ::service_layer::SLGlobalsGetMsgRsp >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
