// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: sl_srte_policy.proto
// </auto-generated>
// Original file comments:
// @file 
// @brief Proto file for Segment-routing traffic-eng (SRTE) Policy RPCs.
// Declares calls for adding, deleting, updating the SRTE policies.
// The GPB data model should reflect the model from the SRTE policy
// RFC https://datatracker.ietf.org/doc/rfc9256/.
// 
// ----------------------------------------------------------------
//  Copyright (c) 2025 by Cisco Systems, Inc.
//  All rights reserved.
// -----------------------------------------------------------------
//
//
//
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace ServiceLayer {
  /// <summary>
  /// @defgroup SLSrtePolicy
  /// Used to programmatically create/update/delete SR-TE policies.
  /// Defines the RPC for operations on SRTE policy.
  ///
  /// @{ 
  /// </summary>
  public static partial class SLSrtePolicy
  {
    static readonly string __ServiceName = "service_layer.SLSrtePolicy";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::ServiceLayer.SLSrPolicyMsg> __Marshaller_service_layer_SLSrPolicyMsg = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::ServiceLayer.SLSrPolicyMsg.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::ServiceLayer.SLSrPolicyRsp> __Marshaller_service_layer_SLSrPolicyRsp = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::ServiceLayer.SLSrPolicyRsp.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::ServiceLayer.SLSrPolicyMsg, global::ServiceLayer.SLSrPolicyRsp> __Method_SLSrPolicyOp = new grpc::Method<global::ServiceLayer.SLSrPolicyMsg, global::ServiceLayer.SLSrPolicyRsp>(
        grpc::MethodType.DuplexStreaming,
        __ServiceName,
        "SLSrPolicyOp",
        __Marshaller_service_layer_SLSrPolicyMsg,
        __Marshaller_service_layer_SLSrPolicyRsp);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::ServiceLayer.SlSrtePolicyReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of SLSrtePolicy</summary>
    [grpc::BindServiceMethod(typeof(SLSrtePolicy), "BindService")]
    public abstract partial class SLSrtePolicyBase
    {
      /// <summary>
      /// The SLSrPolicyOp RPC is used to create/update/delete an SR-TE policy based on the
      /// specified parameters.
      /// </summary>
      /// <param name="requestStream">Used for reading requests from the client.</param>
      /// <param name="responseStream">Used for sending responses back to the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>A task indicating completion of the handler.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task SLSrPolicyOp(grpc::IAsyncStreamReader<global::ServiceLayer.SLSrPolicyMsg> requestStream, grpc::IServerStreamWriter<global::ServiceLayer.SLSrPolicyRsp> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for SLSrtePolicy</summary>
    public partial class SLSrtePolicyClient : grpc::ClientBase<SLSrtePolicyClient>
    {
      /// <summary>Creates a new client for SLSrtePolicy</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public SLSrtePolicyClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for SLSrtePolicy that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public SLSrtePolicyClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected SLSrtePolicyClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected SLSrtePolicyClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      /// <summary>
      /// The SLSrPolicyOp RPC is used to create/update/delete an SR-TE policy based on the
      /// specified parameters.
      /// </summary>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncDuplexStreamingCall<global::ServiceLayer.SLSrPolicyMsg, global::ServiceLayer.SLSrPolicyRsp> SLSrPolicyOp(grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SLSrPolicyOp(new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// The SLSrPolicyOp RPC is used to create/update/delete an SR-TE policy based on the
      /// specified parameters.
      /// </summary>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncDuplexStreamingCall<global::ServiceLayer.SLSrPolicyMsg, global::ServiceLayer.SLSrPolicyRsp> SLSrPolicyOp(grpc::CallOptions options)
      {
        return CallInvoker.AsyncDuplexStreamingCall(__Method_SLSrPolicyOp, null, options);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override SLSrtePolicyClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new SLSrtePolicyClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(SLSrtePolicyBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_SLSrPolicyOp, serviceImpl.SLSrPolicyOp).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, SLSrtePolicyBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_SLSrPolicyOp, serviceImpl == null ? null : new grpc::DuplexStreamingServerMethod<global::ServiceLayer.SLSrPolicyMsg, global::ServiceLayer.SLSrPolicyRsp>(serviceImpl.SLSrPolicyOp));
    }

  }
}
#endregion
